name: lint

on:
  push:
    branches: [ 'main' ]
    tags: [ '*' ]
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8

      - name: Install pipenv
        run: pip install pipenv

      - name: Install quality tools
        run: pipenv install --categories quality

      - name: nblint
        run: pipenv run nblint

      - name: ruff
        run: pipenv run ruff


